### ISSUE TITLE
PETSc path is hard coded in branch hanging node

### ISSUE THREAD

**Issue by KumarSaurabh1992** [paralab/Dendro-KT#4]
PETSc path in hanging node is hard coded in CMAKELists in branch hanging-nodes. This is definitely not the correct way. Just commenting these lines work as long as bashrc is correctly setup. It seems like a path choice of some specific user

if(BUILD_WITH_PETSC)
    list (APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake-modules")
    set(PETSC_DIR $ENV{HOME}/petsc)
    set(PETSC_INCLUDES $ENV{HOME}/petsc)
    set(PETSC_ARCH linux-gnu-c-debug)
    find_package(PETSc REQUIRED)
    add_definitions(-DBUILD_WITH_PETSC)
endif()

Line 3 - 5 should not exist as this cause build to fail.

**Comment by maxishii** [comment]
@KumarSaurabh1992 I added commit 433d63f1. If it still fails then we'll just remove those lines as you suggest.

**Comment by KumarSaurabh1992** [comment]
yes, it works now. Thanks.
